[package]
name = "gh-linguist"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"
linguist-rs = { path = "../../linguist", features = ["default", "github-linguist-yaml"] }
regex = { version = "1.8.1"}

[build-dependencies]
linguist-rs-build = { path = "../../linguist-build" }
